image: python


include:
  - project: "open-source/gitlab-ci-templates"
    ref: "branch/default"
    file:
      - "templates/no-duplicated-ci-pipelines.yml"
      - "templates/lint/check-manifest.yml"
      - "templates/lint/flake8.yml"
      - "templates/lint/black.yml"
      - "templates/lint/mypy.yml"
      - "templates/tests/py3.yml"
      - "templates/create-release-on-heptapod.yml"

stages:
  - lint
  - tests
  - build-push
  - release

build-push-devpi:
  stage: build-push
  only:
    - branch/default
  script:
    - pip install devpi-client
    - devpi use $DEVPI_URL
    - devpi login $DEVPI_LOGIN --password $DEVPI_PWD
    - devpi use dev
    - devpi upload
