default:
  image: python:3.9
  tags:
    - resourcecode-runner

stages:
  - lint
  - tests
  - deployment
  - release
  - publish


check-manifest:
  interruptible: true
  stage: lint
  before_script:
    - pip install tox
  script: tox -e check-manifest

flake8:
  interruptible: true
  stage: lint
  before_script:
    - pip install tox
  script: tox -e flake8

black:
  interruptible: true
  stage: lint
  before_script: 
    - pip install tox
  script: tox -e black

mypy:
  interruptible: true
  stage: lint
  before_script: 
    - pip install tox
  script: tox -e mypy

py3:
  interruptible: true
  stage: tests
  before_script:
    - pip install tox
  script: tox -e py3 -- --junitxml=report.xml -vv
  artifacts:
    when: always
    reports:
      junit: report.xml

doctest:
  stage: tests
  needs: []
  before_script:
    - pip install .
    - pip install sphinx
  script:
    - sphinx-build -b doctest doc .


create-release-on-gitlab:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: never
    - if: '$CI_COMMIT_TAG'
      when: on_success
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG"\
                         --tag-name $CI_COMMIT_TAG

upload-python-package-to-gitlab:
  stage: publish
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: never
    - if: '$CI_COMMIT_TAG'
      when: on_success
  before_script:
    - pip install twine
  script:
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

pypi-publish:
  stage: publish
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: never
    - if: '$CI_COMMIT_TAG'
      when: on_success
  before_script:
    - pip install tox
    - pip install twine
  script:
    - tox -e pypi-publish

pages:
  stage: deployment
  rules:
    - if: '$CI_COMMIT_REF_NAME == "branch/default"'
  before_script:
    - pip install .
    - pip install sphinx sphinx-book-theme
  script:
    - sphinx-build -b html doc public
  artifacts:
    paths:
      - public
