image: python


include:
  - project: "open-source/gitlab-ci-templates"
    ref: "branch/default"
    file:
      - "templates/no-duplicated-ci-pipelines.yml"
      - "templates/lint/check-manifest.yml"
      - "templates/lint/flake8.yml"
      - "templates/lint/black.yml"
      - "templates/lint/mypy.yml"
      - "templates/tests/py3.yml"
      - "templates/create-release-on-heptapod.yml"
      - "templates/upload-python-package-to-heptapod.yml"

stages:
  - lint
  - tests
  - deployment
  - release
  - publish

pages:
  stage: deployment
  rules:
    - if: '$CI_COMMIT_REF_NAME == "branch/default"'
  before_script:
    - pip install .
    - pip install sphinx sphinx-book-theme
  script:
    - sphinx-build -b html doc public
  artifacts:
    paths:
      - public
