name: check
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "27 3 * * 1"

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name:  Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.11.16"
          python-version: "3.11"
          enable-cache: true
      - name: Install tox with tox-uv
        run: uv tool install tox --with tox-uv
      - name: check-manifest
        run: tox -e check-manifest
      - name: flake8
        run: tox -e flake8
      - name: black
        run: tox -e black
      - name: mypy
        run: tox -e mypy

  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.14"
          - "3.13"
          - "3.12"
          - "3.11"
        os:
          - ubuntu-latest
          - macos-13
          - windows-latest
    env:
      MPLBACKEND: Agg  # https://github.com/orgs/community/discussions/26434
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.11.16"
          python-version: ${{ matrix.py }}
          enable-cache: true
      - name: Install tox with tox-uv
        run: uv tool install tox --with tox-uv
      - name: Setup test suite
        run: tox -vv --notest
      - name: Run test suite
        run: tox --skip-pkg-install -e test
